#!/usr/bin/env python3
"""Generate the AWS stencil catalog for the aws-drawio-diagram skill.

Inputs (snapshots under <plugin>/scripts/fixtures/, refresh with scripts/fetch_sources.sh):
  Sidebar-AWS4.js         draw.io palette definitions: names, labels, categories, style pattern
  aws4-stencil-names.txt  every renderable stencil name from stencils/aws4.xml (ground truth)

Outputs:
  references/aws-icons-<section>.md   one markdown table set per palette section
  references/aws-icons-groups.md      grIcon badges + boundary styles without grIcon
  references/aws-icons-general.md     General Resources + Illustrations
  references/aws-icons-retired.md     retired palette (still renders)
  references/aws-icons-legacy.md      renderable stencils absent from the palette
  scripts/stencil-index.json          name -> kind/label/section, read by validate_drawio.py

Usage:
  build_icon_catalog.py [--sidebar PATH] [--stencils PATH] [--out-dir DIR] [--index PATH]
Requires Node.js (runs extract_stencils.js). Build-time only.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter, OrderedDict
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL_DIR = HERE.parent
PLUGIN_DIR = SKILL_DIR.parents[1]
FIXTURES = PLUGIN_DIR / "scripts" / "fixtures"
REFERENCES = SKILL_DIR / "references"

JS_SHAPES = ("group", "group2", "groupCenter", "productIcon", "resourceIcon")
MIN_SERVICE = 300
MIN_RESOURCE = 500

SECTION_SLUGS = {
    "aws4r": "retired",
    "aws4General Resources": "general",
    "aws4Illustrations": "general",
    "aws4Groups": "groups",
}
SECTION_TITLES = {
    "general": "General Resources & Illustrations",
    "groups": "Groups",
    "retired": "Retired (still renders)",
    "legacy": "Legacy stencils (render, not in the palette)",
}
GENERATED_NOTE = (
    "> Generated by `scripts/build_icon_catalog.py` from draw.io `Sidebar-AWS4.js` and "
    "`stencils/aws4.xml` (see `scripts/fixtures/SOURCE.md`). Do not edit by hand — rerun the script."
)

RE_RES = re.compile(r"resIcon=mxgraph\.aws4\.([A-Za-z0-9_]+)")
RE_GR = re.compile(r"grIcon=mxgraph\.aws4\.([A-Za-z0-9_]+)")
RE_SHAPE = re.compile(r"shape=mxgraph\.aws4\.([A-Za-z0-9_]+)")
RE_FILL = re.compile(r"(?:^|;)fillColor=([^;]+)")
RE_STROKE = re.compile(r"(?:^|;)strokeColor=([^;]+)")


def extract(sidebar_js: Path) -> dict:
    """Run the Node harness and return its JSON."""
    proc = subprocess.run(
        ["node", str(HERE / "extract_stencils.js"), str(sidebar_js)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        sys.exit(f"extract_stencils.js failed: {proc.stderr.strip()}")
    return json.loads(proc.stdout)


def load_stencil_names(path: Path) -> set[str]:
    return {ln.strip() for ln in path.read_text().splitlines() if ln.strip() and not ln.startswith("#")}


def slug_for(section_id: str) -> str:
    if section_id in SECTION_SLUGS:
        return SECTION_SLUGS[section_id]
    return section_id.removeprefix("aws4").strip().lower().replace(" ", "-")


def classify(style: str) -> tuple[str, str | None]:
    if m := RE_RES.search(style):
        return "service", m.group(1)
    if m := RE_GR.search(style):
        return "group", m.group(1)
    if (m := RE_SHAPE.search(style)) and m.group(1) not in JS_SHAPES:
        return "resource", m.group(1)
    return "style", None


def _first(regex: re.Pattern, style: str) -> str | None:
    m = regex.search(style)
    return m.group(1) if m else None


def build_index(data: dict, stencil_names: set[str]) -> tuple[dict, list[dict]]:
    stencils: "OrderedDict[str, dict]" = OrderedDict()
    boundaries: list[dict] = []
    for sec in data["sections"]:
        slug = slug_for(sec["id"])
        for e in sec["entries"]:
            kind, name = classify(e["style"])
            label = (e.get("label") or e.get("value") or name or "").strip()
            if kind == "style":
                if slug == "groups":
                    boundaries.append({"label": label, "style": e["style"]})
                continue
            if name in stencils:          # first palette wins …
                prev = stencils[name]
                if kind == "group" and label and label not in prev["label"]:
                    # … except group badges reused with a different meaning (Private/Public subnet
                    # both use group_security_group): keep every label and stroke color.
                    prev["label"] = f"{prev['label']} / {label}"
                    stroke = _first(RE_STROKE, e["style"])
                    if stroke and stroke not in (prev["strokeColor"] or ""):
                        prev["strokeColor"] = f"{prev['strokeColor']} / {stroke}"
                continue
            stencils[name] = {
                "kind": kind,
                "label": label,
                "section": slug,
                "sectionTitle": SECTION_TITLES.get(slug, sec["title"].removeprefix("AWS / ")),
                "fillColor": _first(RE_FILL, e["style"]),
                "strokeColor": _first(RE_STROKE, e["style"]),
                "style": e["style"] if kind == "group" else None,
                "renderable": name in stencil_names,
            }
    for name in sorted(stencil_names - set(stencils)):
        stencils[name] = {
            "kind": "legacy",
            "label": name.replace("_", " "),
            "section": "legacy",
            "sectionTitle": SECTION_TITLES["legacy"],
            "fillColor": None,
            "strokeColor": None,
            "style": None,
            "renderable": True,
        }
    return stencils, boundaries


def _table(rows: list[tuple[str, ...]], header: tuple[str, ...]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def _kind_table(items: list[tuple[str, dict]], kind: str, show_fill: bool) -> str:
    if kind == "service":
        heading = ("## Service-level — `shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.<name>` "
                   "· **strokeColor=#ffffff** · 78×78")
        col = "resIcon"
    else:
        heading = ("## Resource-level — `shape=mxgraph.aws4.<name>` "
                   "· **strokeColor=none** · 48×48 or 78×78")
        col = "shape"
    header = (col, "Display Name") + (("fillColor",) if show_fill else ())
    rows = [
        (f"`{n}`", s["label"] or n) + ((f"`{s['fillColor']}`",) if show_fill else ())
        for n, s in items
    ]
    return heading + "\n" + _table(rows, header)


def _render_section(slug: str, title: str, items: list[tuple[str, dict]]) -> str:
    fills = Counter(s["fillColor"] for _, s in items if s["fillColor"])
    show_fill = len(fills) > 1
    parts = [f"# AWS Icons: {title}", "", GENERATED_NOTE, ""]
    if len(fills) == 1:
        parts += [f"fillColor: `{next(iter(fills))}`", ""]
    elif fills:
        parts += ["fillColor varies per row (see column).", ""]
    if slug == "retired":
        parts += ["These stencils still render but AWS retired the service or replaced the icon. "
                  "Prefer the current icon in the category file; use these only for legacy diagrams.", ""]
    for kind in ("service", "resource"):
        sub = [(n, s) for n, s in items if s["kind"] == kind]
        if sub:
            parts += [_kind_table(sub, kind, show_fill), ""]
    return "\n".join(parts).rstrip() + "\n"


def _render_groups(items: list[tuple[str, dict]], boundaries: list[dict]) -> str:
    parts = ["# AWS Icons: Groups", "", GENERATED_NOTE, "",
             "All groups: `shape=mxgraph.aws4.group;grIcon=mxgraph.aws4.<grIcon>;fillColor=none;container=1;"
             "verticalAlign=top;align=left;spacingLeft=30;`  ", "The badge is the grIcon; the border takes strokeColor.", "",
             "## Group badges (grIcon)"]
    rows = []
    for n, s in items:
        rows.append((f"`{n}`", f"`{s['strokeColor'] or 'none'}`", s["label"] or n))
    parts += [_table(rows, ("grIcon", "strokeColor", "Display Name")), "",
              "## Boundary styles without a badge", "",
              "Use the full style string as-is (add `container=1;` when children live inside).", ""]
    for b in boundaries:
        parts += [f"**{b['label']}**", "", "```", b["style"], "```", ""]
    return "\n".join(parts).rstrip() + "\n"


def _render_legacy(items: list[tuple[str, dict]]) -> str:
    parts = ["# AWS Icons: Legacy stencils", "", GENERATED_NOTE, "",
             "These names exist in draw.io's `aws4.xml` stencil set, so they render, but the current palette "
             "does not list them (renamed or superseded). Use them as resource-level shapes "
             "(`shape=mxgraph.aws4.<name>;strokeColor=none`) or as grIcon badges when the name starts with `group_`. "
             "Prefer the palette name from the category files when one exists.", ""]
    rows = [(f"`{n}`", s["label"]) for n, s in items]
    parts += [_table(rows, ("name", "Guessed Display Name")), ""]
    return "\n".join(parts).rstrip() + "\n"


def render_markdown(stencils: dict, boundaries: list[dict], out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    by_section: "OrderedDict[str, list[tuple[str, dict]]]" = OrderedDict()
    for n, s in stencils.items():
        by_section.setdefault(s["section"], []).append((n, s))
    written: list[Path] = []
    for slug, items in by_section.items():
        title = items[0][1]["sectionTitle"]
        if slug == "groups":
            text = _render_groups(items, boundaries)
        elif slug == "legacy":
            text = _render_legacy(items)
        else:
            text = _render_section(slug, title, items)
        path = out_dir / f"aws-icons-{slug}.md"
        path.write_text(text)
        written.append(path)
    return written


def write_index(stencils: dict, path: Path, sources: dict) -> None:
    slim = {
        n: {k: s[k] for k in ("kind", "label", "section", "fillColor", "strokeColor", "renderable")}
        for n, s in stencils.items()
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(
        {"generated_from": sources, "js_shapes": list(JS_SHAPES), "stencils": slim},
        indent=1, ensure_ascii=False,
    ) + "\n")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sidebar", type=Path, default=FIXTURES / "Sidebar-AWS4.js")
    ap.add_argument("--stencils", type=Path, default=FIXTURES / "aws4-stencil-names.txt")
    ap.add_argument("--out-dir", type=Path, default=REFERENCES)
    ap.add_argument("--index", type=Path, default=HERE / "stencil-index.json")
    args = ap.parse_args(argv)

    data = extract(args.sidebar)
    stencils, boundaries = build_index(data, load_stencil_names(args.stencils))
    counts = Counter(s["kind"] for s in stencils.values())
    if counts["service"] < MIN_SERVICE or counts["resource"] < MIN_RESOURCE:
        print(f"refusing to write: service={counts['service']} resource={counts['resource']} "
              f"(floors {MIN_SERVICE}/{MIN_RESOURCE}); source format changed?", file=sys.stderr)
        return 1
    unrenderable = sorted(n for n, s in stencils.items() if not s["renderable"])
    files = render_markdown(stencils, boundaries, args.out_dir)
    write_index(stencils, args.index, {"sidebar": args.sidebar.name, "stencils": args.stencils.name})
    print(f"wrote {len(files)} reference files to {args.out_dir}")
    print("counts:", dict(counts))
    if unrenderable:
        print("WARNING palette names without a stencil (check draw.io):", ", ".join(unrenderable))
    return 0


if __name__ == "__main__":
    sys.exit(main())
