#!/usr/bin/env python3
"""Ship official AWS icons that draw.io has no stencil for, as draw.io image styles.

  build_extra_icons.py --report [--icons DIR]   list official-pack icons with no matching stencil name
  build_extra_icons.py [--icons DIR]            copy allow-listed SVGs to assets/extra-icons/ and
                                                write references/aws-icons-extra.md

The report is a heuristic (file-name normalization vs stencil names) — review it, then add the icons you
want to scripts/extra-icons.txt as "relative/path.svg|Display Name". Only the allow list is shipped.

Default --icons is the sibling aws-diagram-design plugin's official icon pack (build-time only; nothing in
the shipped skill points there).
"""
from __future__ import annotations

import argparse
import base64
import json
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL_DIR = HERE.parent
PLUGIN_DIR = SKILL_DIR.parents[1]
DEFAULT_ICONS = PLUGIN_DIR.parent / "aws-diagram-design" / "skills" / "aws-diagram-design" / "assets" / "aws-icons"
INDEX = HERE / "stencil-index.json"
ALLOW_LIST = HERE / "extra-icons.txt"
ASSETS = SKILL_DIR / "assets" / "extra-icons"
OUT_MD = SKILL_DIR / "references" / "aws-icons-extra.md"

GENERATED_NOTE = ("> Generated by `scripts/build_extra_icons.py` from `scripts/extra-icons.txt`. "
                  "Do not edit by hand — edit the allow list and rerun.")

_PREFIX = re.compile(r"^(Arch_|Res_|Arch-Category_)")
_SUFFIX = re.compile(r"(_48|_32|_64|_16)?(_Light|_Dark)?\.svg$")
_VENDOR = re.compile(r"^(amazon|aws)[-_]")


def normalize(filename: str) -> str:
    """Official-pack file name -> draw.io-ish stencil name.

    Res_ files are "<Service>_<Resource>"; the resource part alone is what draw.io usually names.
    """
    stem = _SUFFIX.sub("", _PREFIX.sub("", filename))
    if filename.startswith("Res_") and "_" in stem:
        stem = stem.split("_", 1)[1]
    name = re.sub(r"[^a-z0-9]+", "_", stem.lower()).strip("_")
    return _VENDOR.sub("", name)


def _index_names() -> set[str]:
    data = json.loads(INDEX.read_text())
    return set(data["stencils"]) | set(data["js_shapes"])


def report(icons_dir: Path, index_names: set[str]) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for svg in sorted(icons_dir.rglob("*.svg")):
        norm = normalize(svg.name)
        candidates = {norm, f"amazon_{norm}", f"aws_{norm}", norm.replace("_", "")}
        if candidates & index_names:
            continue
        out.append((svg.relative_to(icons_dir).as_posix(), norm))
    return out


def read_allow_list(path: Path) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        rel, _, name = line.partition("|")
        rows.append((rel.strip(), name.strip() or Path(rel.strip()).stem))
    return rows


def image_style(svg_bytes: bytes) -> str:
    # draw.io stores data URIs in cell styles WITHOUT ";base64" because ";" separates style keys.
    b64 = base64.b64encode(svg_bytes).decode("ascii")
    return ("shape=image;aspect=fixed;imageAspect=0;verticalLabelPosition=bottom;verticalAlign=top;"
            "align=center;html=1;fontSize=12;fontColor=#232F3E;sketch=0;"
            f"image=data:image/svg+xml,{b64};")


def build(icons_dir: Path, allow: list[tuple[str, str]], assets_dir: Path, out_md: Path) -> list[Path]:
    assets_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    parts = ["# AWS Icons: Extra (image fallback for icons draw.io lacks)", "", GENERATED_NOTE, "",
             "These official-pack icons have no `mxgraph.aws4` stencil. Use the full style below on a 78×78 "
             "vertex. They are plain images: no `resIcon`, no `strokeColor` rule applies. The SVG files live "
             "in `assets/extra-icons/` for reference; the style already embeds them.", ""]
    for rel, name in allow:
        src = icons_dir / rel
        if not src.exists():
            sys.exit(f"allow-listed icon not found: {src}")
        dst = assets_dir / src.name
        shutil.copyfile(src, dst)
        written.append(dst)
        parts += [f"### {name}", "", f"File: `assets/extra-icons/{src.name}`", "", "```",
                  image_style(src.read_bytes()), "```", ""]
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(parts).rstrip() + "\n")
    written.append(out_md)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--icons", type=Path, default=DEFAULT_ICONS)
    ap.add_argument("--list", type=Path, default=ALLOW_LIST)
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args(argv)
    if not args.icons.is_dir():
        print(f"icon directory not found: {args.icons}", file=sys.stderr)
        return 1
    if args.report:
        for rel, norm in report(args.icons, _index_names()):
            print(f"{norm:50s} {rel}")
        return 0
    files = build(args.icons, read_allow_list(args.list), ASSETS, OUT_MD)
    print(f"wrote {len(files) - 1} icons and {OUT_MD.relative_to(SKILL_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
